apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ../../base/kube-prometheus-stack

patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |
      - op: replace
        path: /spec/values/grafana/ingress/hosts/0
        value: grafana-staging.andlogreg.work
