apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate
data:
  LOG_LEVEL: 'debug'
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  RENOVATE_PLATFORM: 'github'
